### ISSUE TITLE
Installing cc_prompt_settings kills the Cat :\

### ISSUE THREAD

**Issue by HyperUpscale** [team-sviluppo/cc_prompt_settings#1]
When I press install the plugin to change  
Cheshire Cat Prompt Settings by [Team Sviluppo](https://www.teamsviluppo.it/)

That triggers the installation for "cat/plugins/cc_prompt_settings/requirements.txt", 
which tries to install langchain 0.0.279, so pip removes first langchain==0.0.336, while cheshire-cat 1.4.1 requires langchain==0.0.336.

 Which effectively kills the Cat and cannot start anymore, 

"ModuleNotFoundError: No module named 'langchain.embeddings.fastembed'

Is this a known issue ?

**Comment by HyperUpscale** [comment]
![image](https://github.com/team-sviluppo/cc_prompt_settings/assets/126105457/0ec13823-e9ed-41b5-b716-a4e26da2624e)

**Comment by cristianorevil** [comment]
@HyperUpscale 
There was an old reference in reuirements.txt that broke new cat versione, i have fixed. (simply update the repo or wipe content in requirements.txt)
